apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-application-1
  namespace: argocd
spec:
  destination:
    namespace: argocdappdemo
    server: 'https://kubernetes.default.svc'
  source:
    path: Manifests/Deployment
    repoURL: 'https://github.com/Santosh2109-devops/Argocd-Learning.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true